### ISSUE TITLE
[Feature Request] Multiplatform support

### ISSUE THREAD

**Issue by nrobi144** [MobileNativeFoundation/Store#247]
**Is your feature request related to a problem? Please describe.**
It would be nice to migrate the project to support multiplatform projects in the future 

**Describe the solution you'd like**
Multiplatform projects with *native* or *js* targets could possibly make use of the *Store* functionality.
The possible implications:

- A more stricter multiplatform persistence library support for multiplatform projects (SQLDelight)
- Other possible jvm dependency changes & abstractions, like Date & Time
- Current K/N concurrency model restrictions related changes
- New abstractions, native interoperability considerations may also introduce changes

**Additional context**
Since *Store* is a library for the data layer, which is the primary target for multiplatform projects, I believe it would make sense to move in a platform agnostic direction by covering more kotlin targets (However it might make sense to review the JVM and/or Android dependencies more closely)

PS: I'm more then happy to contribute in any format, so let me know if you need any kind of help

**Comment by digitalbuddha** [comment]
Hello! Thank you for the feature request. We've always wanted store to be multiplatform friendly but don't think we can achieve it yet due to our reliance on actors which are currently incompatible with kotlin multiplatform. As kmp matures and adds support for multi threaded coroutines we would definitely want to stop targeting Java only.

**Comment by jimKarsh** [comment]
I would also contribute to this if/when it takes place. Absolutely love the store API for modular our kmm application; currently have it working with no cache layer (yet) and a modified actor for kmp.

**Comment by digitalbuddha** [comment]
Would love to see your impl. If there is a clean way to separate the jvm parts out I don't see any reason not to go kmp.

**Comment by jimKarsh** [comment]
I stole the code snippet here : https://discuss.kotlinlang.org/t/actor-kotlin-common/19569 and replaced the call to jvm actor with this one in StoreRealActor and then ripped out the cache layer. As this was all PoC work I only tested it in an Android application since we're targeting Android first and iOS in the future.

Testing on iOS and reimplementing the cache API with a cross platform alternative is on the road map but I had to punt it down the road.

**Comment by digitalbuddha** [comment]
cc @ychescale9 who has a kotlin version of the cached. Hmm this is looking more possible everyday

**Comment by ychescale9** [comment]
Probably too late for 1.0 but does it make sense to make our cache implementation pluggable?

**Comment by digitalbuddha** [comment]
Yup should be reasonable for 1.1

**Comment by jimKarsh** [comment]
Past few days I've worked on migrating testing over to multiplatform. Had to trade Truth for [Turbine](https://github.com/cashapp/turbine) to implement the `.emitsExactly` testing tool. Additionally, I've had to migrate the TestCoroutineScope to multiplatform (as coroutine-test is not a multiplatform library). So far, everything is passing in jvm and iosX64 but it is sans cache layer. I've commented out tests with `.cache` requests which means quite a bit of functionality is not covered. Additionally, I swapped the implementation out in the sample and it works as expected.

I did everything in a different module so that I could reference the original, however. If you're interested in it I'd be happy to submit a PR. I've kept a running list of changes since it's done in a different module; or I would be happy to move the code into the store4 module for better diffs.

**Comment by digitalbuddha** [comment]
@ychescale9 mind linking to your cache impl?

Would love to see your changes as well. This makes me feel like we can make it work sooner than I thought

**Comment by ychescale9** [comment]
It's not quite ready yet. I setup the KMP project and got ported some tests but haven't done much work since.

I'm hoping to get back to it over Christmas. Will share it as soon as I have a working prototype.

**Comment by ychescale9** [comment]
KMP port of my original kotlin/jvm cache: https://github.com/ReactiveCircus/cache4k

A few notes:

- currently supports jvm, ios, macos, js, but I haven't tested in a real app other than running the tests on those platforms
- implementation is powered by Stately's `IsolateState` and `AtomicReference`
- this is probably not 100% thread-safe as there's no synchronization of those 3 collections (will need to learn how to do it without using a `Lock` in all operations)
- haven't done any benchmarking (I know perf is not great at the moment)

**Comment by beretis** [comment]
Hi guys, can I please ask if this is on the roadmap?

**Comment by digitalbuddha** [comment]
Our internals are built expecting multi threaded coroutines. Once kmp coroutines support access across threads, we will begin working toward compatibility. It's unclear when that will be the case

**Comment by tadfisher** [comment]
`kotlinx.coroutines` has a `native-mt` artifact for experimental native multithreading. Ktor has been using it for some time.

**Comment by digitalbuddha** [comment]
It's on the radar but after the breaking changes in duration experimental apis, we are being more cautious with depending on experimental branches

**Comment by miduch** [comment]
Any updates on this?

**Comment by mirland** [comment]
[The new MM will be merged into the main branch in coroutines 1.6.0](https://github.com/kotlin/kotlinx.coroutines/issues/462#issuecomment-911680792). As it's explained [in this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/2914), [`isExperimentalMM`](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/runtime/src/main/kotlin/kotlin/native/Platform.kt#L139) will be used to know if you can use multi-threading or not. From my point of view, there's no blocker to support multiplatform, because the user can select if the multithreading mode will be used or not. It will be merged into the main branch, so you will not depend on an "experimental branch" What do you think @digitalbuddha? Are you planning to implement it? do you have an estimated time?

**Comment by digitalbuddha** [comment]
Planning to yes but no estimate. We are starting to explore kotlin native. Any help would be appreciated. See @handstandsam

**Comment by digitalbuddha** [comment]
When we do approach we should pull this back in https://github.com/ReactiveCircus/cache4k

**Comment by aclassen** [comment]
After the new memory model release i searched something to try it . so i started to convert store4 to kmp some weeks ago.
I removed everything from the guava cache , but kept the implementation , so it only supports strong references and no loader atm.
I added just a simple 'getOrPut' as a replacement for now. 
Thread safety was achieved using kotlinx-atomicfu.
Performance seems to be very close to original implementation
Also the code could be more kotlin-ish.

So i "finished" converting : cache, filesystem, store and multicast to Android/iOS/JVM
Anyway, still a lot of sample , tests, cleanup work.

I forked Store4 but working in a private repro atm.

**Comment by digitalbuddha** [comment]
Wow sounds awesome! We can make a branch here if you’d like play in the main repo. Excited to see progress

**Comment by aclassen** [comment]
Sure thing. But i created a new project and added module by module as it was too time consuming for me to get the current gradle script working as kmp.
If this is not a problem, i can push a wip version this weekend i guess.

**Comment by digitalbuddha** [comment]
Looks awesome! I created a branch Kmp in case you want to start integrating back into the main repo. I’m excited for the shape this is taking

**Comment by drzby99** [comment]
Hi @digitalbuddha, 

My name is Alan Zhang, an incoming master’s student in CS at the University of Pennsylvania. 

I came across Dropbox’s projects for GSOC, and I’m very interested in contributing to converting Dropbox Store to be a Kotlin multi-platform project or Fusing AndroidX Paging with Dropbox Store (#247). 

Although I don’t have extensive experience with Kotlin, I’m fluent in Java and I’m eager to learn about Kotlin and Android through this experience. To get started, I will first go over the Store’s README. Besides this, is there anything that you recommend to do? 

Look forward to hearing from you!

**Comment by Nurlibay** [comment]
Hello everyone ! I want to participate this project, please allow me join this project

**Comment by digitalbuddha** [comment]
Hi folks hold tight, there will be some messaging from dropbox coming along with how to join the google summer of code projects

**Comment by FossWithKc** [comment]
I'm really interested in this project and want to be a part of it and help develop the software.

**Comment by handstandsam** [comment]
Regarding Google Summer of Code (GSOC), this project is unfortunately no longer going to be participating.

---
@changusmc sent out this message regarding it: https://twitter.com/changusmc/status/1509231084638142467
```
Due to some personnel transitions, Dropbox unfortunately had to pull Store from #GSOC2022. 
We sincerely apologize for the inconvenience.
 ```

**Comment by manosbatsis** [comment]
Just another nudge; would love using this in our multiplatform project.

**Comment by matt-ramotar** [comment]
Hey all - Store now targets Android, iOS, JVM, and JS!

**Comment by beretis** [comment]
@matt-ramotar thats amazing! thanks
