### ISSUE TITLE
[Feature Request] Add converter to StoreBuilder

### ISSUE THREAD

**Issue by matt-ramotar** [MobileNativeFoundation/Store#554]
> Some of the samples demonstrate adding a converter via a StoreBuilder but it looks like that's only possible from MutableStoreBuilder now, is that right?

https://www.reddit.com/r/androiddev/comments/13mb2sz/comment/jkzutgk/?utm_source=share&utm_medium=web2x&context=3

`RealStore` uses the concept of converter but currently it's only possible to configure using `MutableStoreBuilder`

**Comment by digitalbuddha** [comment]
Maybe storebuilder.withConverter?

**Comment by SteinerOk** [comment]
I would like to add a comment as I think this is my case.

Now I am using **Shop4** and the `SourceOfTruth` interface in it has the following signature: `SourceOfTruth<Key, Input, Output>`, which allows me to use different types of reading and writing in `SourceOfTruth` (When I receive data from the network, I modify it and write it to the database, but for reading I already get a different type (a complex combined query in the database), but there is no such possibility in **Store5**, due to its signature for `SourceOfTruth` is `SourceOfTruth<Key : Any, Local : Any>`), which does not allow switching to it.

Could a potential Converter cover this case?

**Comment by SteinerOk** [comment]
I would like to add a comment as I think this is my case.

Now I am using **Store4** and the `SourceOfTruth` interface in it has the following signature: `SourceOfTruth<Key, Input, Output>`, which allows me to use different types of reading and writing in `SourceOfTruth` (When I receive data from the network, I modify it and write it to the database, but for reading I already get a different type (a complex combined query in the database), but there is no such possibility in **Store5**, due to its signature for `SourceOfTruth` is `SourceOfTruth<Key : Any, Local : Any>`), which does not allow switching to it.

Could a potential Converter cover this case?

**Comment by inktomi** [comment]
The documentation shows this as being included already, but as of 5.0.0-beta1 it's not. Note in the docs the return type is `MutableStore` yet the builder used is `StoreBuilder`. 

https://mobilenativefoundation.github.io/Store/mutable-store/building/builder/

**Comment by digitalbuddha** [comment]
Hello! apologies for this breaking change, I'm at a conference this week but will take a look over weekend/next week. I think this was an unintended breaking change from an alpha where we had mutable store being a behavior or store rather than a proxy that you wrap a store with. I'll touch base with other maintainer and figure out a path forward. Apologies for the mess :-)

**Comment by digitalbuddha** [comment]
I don't believe anyone is and contributions are incredibly appreciated
